import Link from "next/link";
import { apiGet, type Health, type Metric } from "@/lib/api";
import { Badge, IncidentsTable, PageHeading, Panel, Unavailable } from "@/components/ui";

export default async function CommandCenter() {
  const [health, telemetry] = await Promise.all([apiGet<Health>("/platform/health"), apiGet<{ items: Metric[] }>("/telemetry/metrics")]);
  if (!health) return <><PageHeading eyebrow="Workspace / Overview" title="Command Center" /><Unavailable /></>;
  const metrics = telemetry?.items ?? [];
  const freshness = metrics.find(item => item.name === "dataset_freshness_minutes");
  return <>
    <PageHeading eyebrow="Workspace / Overview" title="Command Center" hero description="A single view across platform signals, incidents, and downstream impact."
      action={<Link href="/replaylab" className="button button-primary">▷ Start ReplayLab scenario</Link>} />
    <div className="callout block-gap"><strong>Simulated demo environment.</strong> The current fault telemetry is generated by backend ReplayLab adapters. Live Kafka and Spark metric ingestion is not connected.</div>
    <div className="grid grid-5">
      <div className="stat-card accent"><span className="stat-label">Platform health</span><strong>{health.overall_health.score}<span className="small"> / 100</span></strong><span className="stat-foot">Based on current demo signals</span></div>
      <div className="stat-card critical"><span className="stat-label">Active P1</span><strong>{health.active_p1}</strong><span className="stat-foot">Immediate attention</span></div>
      <div className="stat-card warning"><span className="stat-label">Active P2</span><strong>{health.active_p2}</strong><span className="stat-foot">Investigating</span></div>
      <div className="stat-card"><span className="stat-label">Systems degraded</span><strong>{health.systems_degraded}</strong><span className="stat-foot">Of {health.services.length} connected demo signals</span></div>
      <div className="stat-card"><span className="stat-label">Datasets delayed</span><strong>{health.datasets_delayed}</strong><span className="stat-foot">Freshness SLO monitor</span></div>
    </div>
    <div className="grid wide-left section-gap">
      <Panel title="Active incidents" detail={`${health.active_incidents.length} open`}><IncidentsTable incidents={health.active_incidents} /></Panel>
      <Panel title="Platform signals" detail="Current state" variant="holographic"><div className="service-list">
        {health.services.map(service => <div className="service-row" key={service.name}><span className="service-icon">{service.name[0]}</span><span className="service-name">{service.name}</span><Badge tone={service.status === "healthy" ? "success" : "critical"}>{service.status}</Badge><span className="service-score">{service.score}</span></div>)}
      </div></Panel>
    </div>
    <div className="grid grid-2 section-gap">
      <Panel title="Business impact" detail="Derived from data health"><div className="panel-body"><div className="grid grid-3">
        <div><div className="text-faint small">FRESHNESS</div><h2 className="mono">{freshness ? `${freshness.value}m` : "—"}</h2></div>
        <div><div className="text-faint small">DASHBOARDS</div><h2 className="mono">{health.business_impact.affected_dashboards}</h2></div>
        <div><div className="text-faint small">SLO RISK</div><h2><Badge tone={health.business_impact.slo_at_risk ? "warning" : "success"}>{health.business_impact.slo_at_risk ? "AT RISK" : "CLEAR"}</Badge></h2></div>
      </div><p className="text-faint small">Only the seeded orders pipeline is represented in demo mode.</p></div></Panel>
      <Panel title="Operating loop" detail="Detect → Verify" variant="terminal"><div className="panel-body"><div className="terminal-line"><span className="terminal-prompt">&gt;</span> observe --pipeline orders <span className="terminal-cursor" aria-hidden="true">_</span></div><p className="terminal-description">Start a fault scenario, review its evidence and blast radius, approve the demo recovery, then inspect verification and the postmortem.</p><Link href="/replaylab" className="table-link">Open ReplayLab →</Link></div></Panel>
    </div>
    <p className="page-footer">InvestiNator · See the signal. Find the cause. Fix with confidence.</p>
  </>;
}
