"""initial operational schema

Revision ID: bf50bd87cb88
Revises:
"""
from alembic import op
import sqlalchemy as sa


revision = 'bf50bd87cb88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('task', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_tenant_id'), 'ai_usage', ['tenant_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_incident_action', 'approvals', ['tenant_id', 'incident_id', 'action_id'], unique=True)
    op.create_index(op.f('ix_approvals_incident_id'), 'approvals', ['incident_id'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_incident_id'), 'audit_events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_tenant_id'), 'entities', ['tenant_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('replay_id', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_tenant_id'), 'evaluations', ['tenant_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('technology', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_index('ix_incidents_tenant_status_created', 'incidents', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('technology', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=20000), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_tenant_id'), 'knowledge_documents', ['tenant_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('target_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_source_id'), 'relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_id'), 'relationships', ['target_id'], unique=False)
    op.create_index(op.f('ix_relationships_tenant_id'), 'relationships', ['tenant_id'], unique=False)
    op.create_table('replay_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('scenario', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_runs_tenant_id'), 'replay_runs', ['tenant_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('signal_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_entity_id'), 'telemetry', ['entity_id'], unique=False)
    op.create_index(op.f('ix_telemetry_name'), 'telemetry', ['name'], unique=False)
    op.create_index(op.f('ix_telemetry_observed_at'), 'telemetry', ['observed_at'], unique=False)
    op.create_index(op.f('ix_telemetry_signal_type'), 'telemetry', ['signal_type'], unique=False)
    op.create_index(op.f('ix_telemetry_tenant_id'), 'telemetry', ['tenant_id'], unique=False)
    op.create_index('ix_telemetry_tenant_name_time', 'telemetry', ['tenant_id', 'name', 'observed_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_entity_id'), 'alerts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_alerts_incident_id'), 'alerts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=10000), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_incident_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_entity_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_telemetry_tenant_name_time', table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_tenant_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_signal_type'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_observed_at'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_name'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_entity_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_replay_runs_tenant_id'), table_name='replay_runs')
    op.drop_table('replay_runs')
    op.drop_index(op.f('ix_relationships_tenant_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_target_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_knowledge_documents_tenant_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index('ix_incidents_tenant_status_created', table_name='incidents')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_evaluations_tenant_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_entities_tenant_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_incident_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_incident_id'), table_name='approvals')
    op.drop_index('ix_approval_incident_action', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_ai_usage_tenant_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
